<?php
/**
 * Maintenance Page
 *
 * @copyright Scandiweb, Inc. All rights reserved.
 */

?>
<script>
    // browser should execute this synchronously so content shouldn't jump
    // this metatag is required for proper media queries and general styling
    // but Magento in page.phtml doesn't set it
    var metaTag = document.createElement('meta');

    metaTag.setAttribute('name', 'viewport');
    metaTag.setAttribute('content', 'width=device-width, initial-scale=1');

    document.head.append(metaTag);
</script>
<style>
    body {
        background-color: #f9f9f9;
        font-family: Arial, sans-serif;
        font-size: 1rem;
        color: #333;
        margin: 0;
        padding: 0;
        height: 100vh;
        display: flex;
        align-items: center;
        justify-content: center;
        flex-direction: column;
        text-align: center;
    }

    .description {
        display: flex;
        flex-direction: column;
        justify-content: flex-start;
        text-align: left;
    }

    @media screen and (min-width: 768px) {
        .description > h1 {
            font-size: 3.5rem;
        }
        .description > p {
            font-size: 1.5rem;
        }
    }
</style>

<div class="description">
    <h1>We'll Be Back Soon</h1>
    <p>
        Our website is currently under maintenance. <br />
        Thank you for your patience.
    </p>
</div>
